// Translations for the "My breeding" card (all app languages).
type T = { title: string; desc: string; country: string; name: string; address: string; rename: string; n1: string; n2: string; note: string; save: string; saved: string; error: string; other: string };

const D: Record<string, T> = {
  fr: { title: "Mon élevage", desc: "Vos autorisations, affichables en en-tête du registre imprimé.", country: "Pays", name: "Nom de l'élevage", address: "Adresse de l'élevage", rename: "Modifier le nom des autorisations", n1: "Nom autorisation 1", n2: "Nom autorisation 2", note: "Les intitulés sont indicatifs : vérifiez la réglementation de votre pays ou région.", save: "Enregistrer", saved: "Informations de l'élevage enregistrées", error: "Erreur lors de l'enregistrement", other: "Autre pays" },
  en: { title: "My breeding facility", desc: "Your permits, shown at the top of the printed register.", country: "Country", name: "Facility name", address: "Facility address", rename: "Edit permit names", n1: "Permit 1 name", n2: "Permit 2 name", note: "Labels are indicative: check the regulations of your country or region.", save: "Save", saved: "Facility information saved", error: "Error while saving", other: "Other country" },
  es: { title: "Mi criadero", desc: "Sus autorizaciones, visibles en el encabezado del registro impreso.", country: "País", name: "Nombre del criadero", address: "Dirección del criadero", rename: "Modificar el nombre de las autorizaciones", n1: "Nombre autorización 1", n2: "Nombre autorización 2", note: "Los nombres son orientativos: consulte la normativa de su país o región.", save: "Guardar", saved: "Información del criadero guardada", error: "Error al guardar", other: "Otro país" },
  de: { title: "Meine Zucht", desc: "Ihre Genehmigungen, im Kopf des gedruckten Bestandsbuchs angezeigt.", country: "Land", name: "Name der Zucht", address: "Adresse der Zucht", rename: "Namen der Genehmigungen ändern", n1: "Name Genehmigung 1", n2: "Name Genehmigung 2", note: "Die Bezeichnungen sind Richtwerte: Prüfen Sie die Vorschriften Ihres Landes oder Ihrer Region.", save: "Speichern", saved: "Zuchtinformationen gespeichert", error: "Fehler beim Speichern", other: "Anderes Land" },
  it: { title: "Il mio allevamento", desc: "Le tue autorizzazioni, mostrate nell'intestazione del registro stampato.", country: "Paese", name: "Nome dell'allevamento", address: "Indirizzo dell'allevamento", rename: "Modifica il nome delle autorizzazioni", n1: "Nome autorizzazione 1", n2: "Nome autorizzazione 2", note: "Le diciture sono indicative: verifica la normativa del tuo paese o regione.", save: "Salva", saved: "Informazioni dell'allevamento salvate", error: "Errore durante il salvataggio", other: "Altro paese" },
  pt: { title: "O meu criadouro", desc: "As suas autorizações, exibidas no cabeçalho do registo impresso.", country: "País", name: "Nome do criadouro", address: "Morada do criadouro", rename: "Alterar o nome das autorizações", n1: "Nome autorização 1", n2: "Nome autorização 2", note: "As designações são indicativas: verifique a legislação do seu país ou região.", save: "Guardar", saved: "Informações do criadouro guardadas", error: "Erro ao guardar", other: "Outro país" },
  nl: { title: "Mijn kwekerij", desc: "Uw vergunningen, getoond bovenaan het afgedrukte register.", country: "Land", name: "Naam kwekerij", address: "Adres kwekerij", rename: "Namen van vergunningen wijzigen", n1: "Naam vergunning 1", n2: "Naam vergunning 2", note: "Benamingen zijn indicatief: controleer de regelgeving van uw land of regio.", save: "Opslaan", saved: "Kwekerijgegevens opgeslagen", error: "Fout bij opslaan", other: "Ander land" },
  pl: { title: "Moja hodowla", desc: "Twoje zezwolenia, widoczne w nagłówku wydrukowanego rejestru.", country: "Kraj", name: "Nazwa hodowli", address: "Adres hodowli", rename: "Zmień nazwy zezwoleń", n1: "Nazwa zezwolenia 1", n2: "Nazwa zezwolenia 2", note: "Nazwy są orientacyjne: sprawdź przepisy swojego kraju lub regionu.", save: "Zapisz", saved: "Dane hodowli zapisane", error: "Błąd zapisu", other: "Inny kraj" },
  ru: { title: "Мой питомник", desc: "Ваши разрешения, отображаемые в шапке печатного журнала.", country: "Страна", name: "Название питомника", address: "Адрес питомника", rename: "Изменить названия разрешений", n1: "Название разрешения 1", n2: "Название разрешения 2", note: "Названия ориентировочные: проверьте законодательство вашей страны или региона.", save: "Сохранить", saved: "Данные питомника сохранены", error: "Ошибка сохранения", other: "Другая страна" },
  ja: { title: "私のブリーディング施設", desc: "印刷される台帳の上部に表示される許可情報。", country: "国", name: "施設名", address: "施設の住所", rename: "許可の名称を変更", n1: "許可1の名称", n2: "許可2の名称", note: "名称は目安です。お住まいの国・地域の規制をご確認ください。", save: "保存", saved: "施設情報を保存しました", error: "保存中にエラーが発生しました", other: "その他の国" },
  zh: { title: "我的繁育场", desc: "您的许可证，可显示在打印登记簿的页眉。", country: "国家", name: "繁育场名称", address: "繁育场地址", rename: "修改许可证名称", n1: "许可证1名称", n2: "许可证2名称", note: "名称仅供参考：请核实您所在国家或地区的法规。", save: "保存", saved: "繁育场信息已保存", error: "保存出错", other: "其他国家" },
  hi: { title: "मेरा प्रजनन केंद्र", desc: "आपके परमिट, मुद्रित रजिस्टर के शीर्ष पर दिखाए जाते हैं।", country: "देश", name: "केंद्र का नाम", address: "केंद्र का पता", rename: "परमिट के नाम बदलें", n1: "परमिट 1 का नाम", n2: "परमिट 2 का नाम", note: "नाम सांकेतिक हैं: अपने देश या क्षेत्र के नियम जांचें।", save: "सहेजें", saved: "केंद्र की जानकारी सहेजी गई", error: "सहेजने में त्रुटि", other: "अन्य देश" },
  pa: { title: "ਮੇਰਾ ਪ੍ਰਜਨਨ ਕੇਂਦਰ", desc: "ਤੁਹਾਡੇ ਪਰਮਿਟ, ਛਪੇ ਰਜਿਸਟਰ ਦੇ ਸਿਰਲੇਖ ਵਿੱਚ ਦਿਖਾਏ ਜਾਂਦੇ ਹਨ।", country: "ਦੇਸ਼", name: "ਕੇਂਦਰ ਦਾ ਨਾਮ", address: "ਕੇਂਦਰ ਦਾ ਪਤਾ", rename: "ਪਰਮਿਟਾਂ ਦੇ ਨਾਮ ਬਦਲੋ", n1: "ਪਰਮਿਟ 1 ਦਾ ਨਾਮ", n2: "ਪਰਮਿਟ 2 ਦਾ ਨਾਮ", note: "ਨਾਮ ਸੰਕੇਤਕ ਹਨ: ਆਪਣੇ ਦੇਸ਼ ਜਾਂ ਖੇਤਰ ਦੇ ਨਿਯਮ ਜਾਂਚੋ।", save: "ਸੰਭਾਲੋ", saved: "ਕੇਂਦਰ ਦੀ ਜਾਣਕਾਰੀ ਸੰਭਾਲੀ ਗਈ", error: "ਸੰਭਾਲਣ ਵਿੱਚ ਗਲਤੀ", other: "ਹੋਰ ਦੇਸ਼" },
  ta: { title: "என் இனப்பெருக்க மையம்", desc: "உங்கள் அனுமதிகள், அச்சிடப்பட்ட பதிவேட்டின் தலைப்பில் காட்டப்படும்.", country: "நாடு", name: "மையத்தின் பெயர்", address: "மையத்தின் முகவரி", rename: "அனுமதிகளின் பெயர்களை மாற்று", n1: "அனுமதி 1 பெயர்", n2: "அனுமதி 2 பெயர்", note: "பெயர்கள் குறிப்புக்கானவை: உங்கள் நாடு அல்லது பகுதியின் விதிகளைச் சரிபார்க்கவும்.", save: "சேமி", saved: "மையத் தகவல் சேமிக்கப்பட்டது", error: "சேமிப்பதில் பிழை", other: "பிற நாடு" },
  th: { title: "ฟาร์มของฉัน", desc: "ใบอนุญาตของคุณ แสดงที่ส่วนหัวของทะเบียนที่พิมพ์", country: "ประเทศ", name: "ชื่อฟาร์ม", address: "ที่อยู่ฟาร์ม", rename: "แก้ไขชื่อใบอนุญาต", n1: "ชื่อใบอนุญาต 1", n2: "ชื่อใบอนุญาต 2", note: "ชื่อเป็นเพียงแนวทาง: โปรดตรวจสอบกฎหมายของประเทศหรือภูมิภาคของคุณ", save: "บันทึก", saved: "บันทึกข้อมูลฟาร์มแล้ว", error: "เกิดข้อผิดพลาดในการบันทึก", other: "ประเทศอื่น" },
  id: { title: "Penangkaran saya", desc: "Izin Anda, ditampilkan di kepala register yang dicetak.", country: "Negara", name: "Nama penangkaran", address: "Alamat penangkaran", rename: "Ubah nama izin", n1: "Nama izin 1", n2: "Nama izin 2", note: "Nama bersifat indikatif: periksa peraturan negara atau wilayah Anda.", save: "Simpan", saved: "Informasi penangkaran disimpan", error: "Gagal menyimpan", other: "Negara lain" },
};

export const breederT = (lang?: string): T => D[(lang || "en").slice(0, 2)] || D.en;
